// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.request
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class RequestTransport : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"RequestTransport\",\"namespace\":\"eu.driver.model.sim.reque" +
				"st\",\"fields\":[{\"name\":\"id\",\"doc\":\"Unique identifier of the request\",\"type\":\"stri" +
				"ng\"},{\"name\":\"applicant\",\"doc\":\"Unique identifier of the connected application s" +
				"ending the request\",\"type\":\"string\"},{\"name\":\"entity\",\"doc\":\"Unique identifier o" +
				"f the entity the applicant requests to be transported\",\"type\":\"string\"},{\"name\":" +
				"\"destination\",\"doc\":\"Unique identifier of the entity the applicant requests the " +
				"given entity to transport to\",\"type\":\"string\"},{\"name\":\"route\",\"doc\":\"Optional l" +
				"ist of locations, creating an edge between every consecutive location in the lis" +
				"t defining the preferred route of the transport\",\"default\":null,\"type\":[\"null\",{" +
				"\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Location\",\"namespace\":\"eu.driver" +
				".model.sim.support\",\"fields\":[{\"name\":\"latitude\",\"doc\":\"In decimal degrees, rang" +
				"ing from [-90, 90] where 0 is the equator\",\"type\":\"double\"},{\"name\":\"longitude\"," +
				"\"doc\":\"In decimal degrees, ranging from (-180, 180] where 0 is the Prime Meridia" +
				"n (line going through the geographic north, Greenwich, and the geographic south)" +
				"\",\"type\":\"double\"},{\"name\":\"altitude\",\"doc\":\"Optional in meters, where 0 is the " +
				"surface of the WGS84-based ellipsoid\",\"default\":null,\"type\":[\"null\",\"double\"]}]}" +
				"}]},{\"name\":\"tags\",\"doc\":\"Optional map containing transport request specific inf" +
				"ormation: key – unique name of the specific property; value – value of that prop" +
				"erty\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]}],\"_commen" +
				"t\":\"\"}");
		/// <summary>
		/// Unique identifier of the request
		/// </summary>
		private string _id;
		/// <summary>
		/// Unique identifier of the connected application sending the request
		/// </summary>
		private string _applicant;
		/// <summary>
		/// Unique identifier of the entity the applicant requests to be transported
		/// </summary>
		private string _entity;
		/// <summary>
		/// Unique identifier of the entity the applicant requests the given entity to transport to
		/// </summary>
		private string _destination;
		/// <summary>
		/// Optional list of locations, creating an edge between every consecutive location in the list defining the preferred route of the transport
		/// </summary>
		private IList<eu.driver.model.sim.support.Location> _route;
		/// <summary>
		/// Optional map containing transport request specific information: key – unique name of the specific property; value – value of that property
		/// </summary>
		private IDictionary<string,System.String> _tags;
		public virtual Schema Schema
		{
			get
			{
				return RequestTransport._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the request
		/// </summary>
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// Unique identifier of the connected application sending the request
		/// </summary>
		public string applicant
		{
			get
			{
				return this._applicant;
			}
			set
			{
				this._applicant = value;
			}
		}
		/// <summary>
		/// Unique identifier of the entity the applicant requests to be transported
		/// </summary>
		public string entity
		{
			get
			{
				return this._entity;
			}
			set
			{
				this._entity = value;
			}
		}
		/// <summary>
		/// Unique identifier of the entity the applicant requests the given entity to transport to
		/// </summary>
		public string destination
		{
			get
			{
				return this._destination;
			}
			set
			{
				this._destination = value;
			}
		}
		/// <summary>
		/// Optional list of locations, creating an edge between every consecutive location in the list defining the preferred route of the transport
		/// </summary>
		public IList<eu.driver.model.sim.support.Location> route
		{
			get
			{
				return this._route;
			}
			set
			{
				this._route = value;
			}
		}
		/// <summary>
		/// Optional map containing transport request specific information: key – unique name of the specific property; value – value of that property
		/// </summary>
		public IDictionary<string,System.String> tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				this._tags = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.applicant;
			case 2: return this.entity;
			case 3: return this.destination;
			case 4: return this.route;
			case 5: return this.tags;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.applicant = (System.String)fieldValue; break;
			case 2: this.entity = (System.String)fieldValue; break;
			case 3: this.destination = (System.String)fieldValue; break;
			case 4: this.route = (IList<eu.driver.model.sim.support.Location>)fieldValue; break;
			case 5: this.tags = (IDictionary<string,System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
